# Generated by Django 5.1.1 on 2025-10-12 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Adzora', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('featured_video_heading', models.CharField(default='Featured Showcase', max_length=120)),
                ('footer_text', models.CharField(default='© Adzora. All rights reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text='Optional CSS class for the icon (e.g. fa-brands fa-instagram).', max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=5)),
                ('light_background', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color value (e.g. #1A1A1A).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('light_surface', models.CharField(default='#f4f4f5', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color value (e.g. #1A1A1A).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('light_text', models.CharField(default='#1f2933', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color value (e.g. #1A1A1A).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('light_accent', models.CharField(default='#f97316', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color value (e.g. #1A1A1A).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('dark_background', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color value (e.g. #1A1A1A).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('dark_surface', models.CharField(default='#1f2937', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color value (e.g. #1A1A1A).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('dark_text', models.CharField(default='#f9fafb', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color value (e.g. #1A1A1A).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
                ('dark_accent', models.CharField(default='#38bdf8', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color value (e.g. #1A1A1A).', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')])),
            ],
            options={
                'verbose_name': 'Theme settings',
            },
        ),
    ]
