# Generated by Django 5.2.6 on 2025-10-17 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationLink',
        ),
        migrations.DeleteModel(
            name='ThemeSettings',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='featured_video_heading',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='footer_text',
        ),
    ]
