"""
Django settings for adzora_backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v^iz!247v@yl@zj0&p@69j81d5%p@!=!u-p^vx_&q94=%d5895'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'content',
    'media_library',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'adzora_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'adzora_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS: list[Path] = []

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',
    ),
}

CORS_ALLOWED_ORIGINS: list[str] = []
CORS_ALLOW_ALL_ORIGINS = True  # Development default; tighten for production
CORS_ALLOW_CREDENTIALS = True


JAZZMIN_SETTINGS = {
    'site_title': 'Adzora Admin',
    'site_header': 'Adzora Studio',
    'welcome_sign': 'Hi Adzora team 👋',
    'copyright': 'Adzora',
    'show_sidebar': True,
    'navigation_expanded': False,
    'site_logo_classes': 'img-responsive',
    'site_brand': 'Adzora',
    'topmenu_links': [
        {'app': 'content'},
        {'app': 'media_library'},
        {'name': 'Public Site', 'url': '/', 'new_window': False},
    ],
    'order_with_respect_to': (
        'content.SiteConfiguration',
        'content.ThemeSettings',
        'content.NavigationLink',
        'content.SocialLink',
        'media_library.Category',
        'media_library.Video',
        'media_library.ImageAsset',
        'media_library.Tag',
    ),
    'icons': {
        'content.SiteConfiguration': 'fas fa-rocket',
        'content.ThemeSettings': 'fas fa-palette',
        'content.NavigationLink': 'fas fa-bars',
        'content.SocialLink': 'fab fa-hashtag',
        'media_library.Category': 'fas fa-folder-tree',
        'media_library.Video': 'fas fa-video',
        'media_library.ImageAsset': 'fas fa-images',
        'media_library.Tag': 'fas fa-tags',
    },
    'usermenu_links': [
        {'model': 'auth.user'},
    ],
    'related_modal_active': False,
    'custom_css': None,
    'custom_js': None,
    'hide_models': [],
    'theme': 'flatly',
    'changeform_format': 'horizontal_tabs',
    'changeform_format_overrides': {
        'content.SiteConfiguration': 'single',
        'content.ThemeSettings': 'single',
    },
}
