name: Deploy frontend to Namecheap (FTPS)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: FTP Deploy (FTPS)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SFTP_HOST }}   # server196.web-hosting.com
          username: ${{ secrets.SFTP_USER }} # deploy@adzora.net
          password: ${{ secrets.SFTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: frontend/
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.DS_Store
            **/node_modules/**
